name: Build and Release WikiBreeze 
on: 
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive project
        run: |
          mkdir ./WikiBreeze-${{ matrix.os }}
          mv ./Wikibreeze ./WikiBreeze-${{ matrix.os }}/
      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WikiBreeze-${{ matrix.os }}-build
          path: ./WikiBreeze-${{ matrix.os }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Download Windows artifact  
      - name: Download Windows built artifact 
        if: contains(needs.build.outputs.os, 'windows-latest')
        uses: actions/download-artifact@v2
        with: 
          name: WikiBreeze-windows-latest-build
      # Upload Windows release asset  
      - name: Upload Windows Release Asset
        if: contains(needs.build.outputs.os, 'windows-latest')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  
          asset_path: ./WikiBreeze-windows-latest-build/WikiBreeze.zip  
          asset_name: WikiBreeze-Windows.zip  
          asset_content_type: application/zip 
      # Download Linux artifact
      - name: Download Linux built binaries
        if: contains(needs.build.outputs.os, 'ubuntu-latest') 
        uses: actions/download-artifact@v2
        with: 
          name: WikiBreeze-ubuntu-latest-build
          path: ./
      # Upload Linux release asset  
      - name: Upload Linux Release Asset
        if: contains(needs.build.outputs.os, 'ubuntu-latest')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  
          asset_path: ./WikiBreeze.zip  
          asset_name: WikiBreeze-Linux.zip  
          asset_content_type: application/zip
