name: Build WikiBreeze
# name: Build and Release WikiBreeze
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/README_zh.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      
      - name: Get latest tag 
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get_latest_tag
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          
      - name: Install dependencies
        run: npm install 
        
      - name: Build frontend  
        run: npm run build:frontend
    
      - name: Build for linux         
        run: |
          env GOOS=linux GOARCH=amd64 npm run build:backend 
          mkdir ./WikiBreeze-linux
          cp -r ./Wikibreeze ./WikiBreeze-linux
          rm ./Wikibreeze/WikiBreeze
          cd ./WikiBreeze-linux
          zip -r WikiBreeze-linux-${{ steps.get-latest-tag.outputs.tag }}.zip Wikibreeze         
        
      - name: Build for macos         
        run: |
          env GOOS=darwin GOARCH=amd64 npm run build:backend
          mkdir ./WikiBreeze-macos
          cp -r ./Wikibreeze ./WikiBreeze-macos
          rm ./Wikibreeze/WikiBreeze
          cd ./WikiBreeze-macos
          zip -r WikiBreeze-macos-${{ steps.get-latest-tag.outputs.tag }}.zip Wikibreeze
        
      - name: Build for Windows         
        run: |
          env GOOS=windows GOARCH=amd64 npm run build:backend
          mkdir ./WikiBreeze-windows
          cp -r ./Wikibreeze ./WikiBreeze-windows
          rm ./Wikibreeze/WikiBreeze.exe
          cd ./WikiBreeze-windows
          zip -r WikiBreeze-windows-${{ steps.get-latest-tag.outputs.tag }}.zip Wikibreeze
        
      - name: Upload Linux zip
        uses: actions/upload-artifact@v2 
        with:
          name: WikiBreeze-linux-${{ steps.get-latest-tag.outputs.tag }}.zip
          path: ./WikiBreeze-linux/WikiBreeze-linux-${{ steps.get-latest-tag.outputs.tag }}.zip  

      - name: Upload MacOS zip  
        uses: actions/upload-artifact@v2 
        with:
          name: WikiBreeze-macos-${{ steps.get-latest-tag.outputs.tag }}.zip
          path: ./WikiBreeze-linux/WikiBreeze-linux-${{ steps.get-latest-tag.outputs.tag }}.zip 

      - name: Upload Windows zip
        uses: actions/upload-artifact@v2    
        with:
          name: WikiBreeze-windows-${{ steps.get-latest-tag.outputs.tag }}.zip
          path: ./WikiBreeze-linux/WikiBreeze-linux-${{ steps.get-latest-tag.outputs.tag }}.zip

            
          
#   release:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:   
#       # Upload Linux release asset 
#       - name: Upload Linux Release Asset     
#         uses: actions/upload-release-asset@v1
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }} 
#           asset_path: ./WikiBreeze-linux/Wikibreeze
#           asset_name: WikiBreeze-Linux.zip
#           asset_content_type: application/zip         
#       # Upload MacOS release asset 
#       - name: Upload MacOS Release Asset     
#         uses: actions/upload-release-asset@v1
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }} 
#           asset_path: ./WikiBreeze-macos/Wikibreeze  
#           asset_name: WikiBreeze-MacOS.zip
#           asset_content_type: application/zip         
#       # Upload Windows release asset 
#       - name: Upload Windows Release Asset     
#         uses: actions/upload-release-asset@v1
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }} 
#           asset_path: ./WikiBreeze-windows/Wikibreeze  
#           asset_name: WikiBreeze-Windows.exe
#           asset_content_type: application/x-msdownload
