name: Build and Release WikiBreeze
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md/*.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          
      - name: Install dependencies
        run: npm install 
        
      - name: Build for Linux         
        run: env GOOS=linux GOARCH=amd64 npm run build   
        
      - name: Build for macOS         
        run: env GOOS=darwin GOARCH=amd64 npm run build  
        
      - name: Build for Windows         
        run: env GOOS=windows GOARCH=amd64 npm run build   
        
      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WikiBreeze-linux-build
          path: ./dist/wikiBreeze-linux
          
      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WikiBreeze-macos-build
          path: ./dist/wikiBreeze-darwin   
          
      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WikiBreeze-windows-build
          path: ./dist/wikiBreeze-windows.exe  
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:   
      # Upload Linux release asset 
      - name: Upload Linux Release Asset     
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./WikiBreeze-linux-build/wikiBreeze-linux
          asset_name: WikiBreeze-Linux.zip
          asset_content_type: application/zip         
      # Upload MacOS release asset 
      - name: Upload MacOS Release Asset     
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./WikiBreeze-macos-build/wikiBreeze-darwin
          asset_name: WikiBreeze-MacOS.zip
          asset_content_type: application/zip         
      # Upload Windows release asset 
      - name: Upload Windows Release Asset     
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./WikiBreeze-windows-build/wikiBreeze-windows.exe
          asset_name: WikiBreeze-Windows.exe
          asset_content_type: application/x-msdownload
